### ISSUE TITLE
Initial Implementation

### ISSUE THREAD

**Issue by KodrAus** [KodrAus/nuget-rs#1]
Simplest implementation: Build a nuget package with a build for the local target. For nuget we could use the `any` rid, but I'd like to get a toe in the water for cross compilation and think about how to go from a Rust triple to a .NET rid.

# TODO

- [x] Parse `Cargo.toml`
- [x] Run `cargo build`
- [x] Convert toml to nuspec
- [x] Build `nupkg`
- [x] Save `nupkg`
- [x] Standardise `PathBuf`/`&Path`/`String`/`&str`/`Cow<'a, str>` usage
- [x] Add tests for nuget bits

**Comment by KodrAus** [comment]
We're currently not capturing the arch for the cargo build, but checking it for nuget. This would need to change in the future. I think we'll probably end up capturing most of the Rust triple eventually.

**Comment by KodrAus** [comment]
A test we can run in proper CI environments that makes sure the builds work properly would be good, right now I'm just building this on Windows.

**Comment by KodrAus** [comment]
OK this is on the right track. The nuget pack stuff is still a bit messy, since it was a pain to get it working. All it needs is a proper step to write the package and it's good to go.

**Comment by KodrAus** [comment]
Something to start thinking about is supplying your own nuspec file and library binary. This would mean parsing the nuspec to find version and id information, and knowing the target for the library.

Maybe something like:

```
cargo nuget --nuspec ./MyPkg.nuspec --target-win-x64 ./target/debug/pkg.dll
```

Supplying a nuspec should skip cargo parse and build and supplying a target lib should skip cargo build. That way it should be possible to supply a pre-built lib while still using cargo metadata.

**Comment by KodrAus** [comment]
I think I'll change the dependencies to take strongly typed inputs instead of statics, but not expose them directly to the CLI yet. That will need some thought.

**Comment by KodrAus** [comment]
I'll write a `nom` parser for testing outputs that strips whitespace, using `multispace` or something. That way we can have a nicer experience testing XML output.

This also needs a build script that runs in Travis and appveyor and verifies packages can be used (just use the test directory).

**Comment by KodrAus** [comment]
OK I'm just going to `Cow` all the things. That's the simplest way to go to support future extensions

**Comment by KodrAus** [comment]
The things have all been `Cow`'d. I can probably clean up some of the conversion logic, so will take a look at that next.

**Comment by KodrAus** [comment]
Should add a test to ensure you get an error when packing nuget with either only an unknown or no targets.
